//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BridgeLogSave
    {
        public int BridgeLogSaveID { get; set; }
        public int ActID { get; set; }
        public int UserID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime SavedUtc { get; set; }
        public string UnifiedLogText { get; set; }
        public string StatusJson { get; set; }
        public string MavlinkJson { get; set; }
    
        public virtual Act Act { get; set; }
        public virtual UsersProfile UsersProfile { get; set; }
    }
}
