//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Error()
        {
            this.Inspection = new HashSet<Inspection>();
            this.Description = new HashSet<Description>();
        }
    
        public int ErrorID { get; set; }
        public Nullable<int> TMID { get; set; }
        public int PlaceID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ProductID { get; set; }
        public bool inProgress { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Product Product { get; set; }
        public virtual TechnicalMapFull TechnicalMapFull { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Description> Description { get; set; }
    }
}
