//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int InspectionID { get; set; }
        public int UserID { get; set; }
        public int ErrorID { get; set; }
        public int DescriptionID { get; set; }
        public int ResultID { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual Error Error { get; set; }
        public virtual ResultTable ResultTable { get; set; }
        public virtual UsersProfile UsersProfile { get; set; }
    }
}
