//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPhoto
    {
        public int ProductPhotoID { get; set; }
        public int ProductID { get; set; }
        public int SequenceNo { get; set; }
        public byte Stage { get; set; }
        public Nullable<int> TMAID { get; set; }
        public Nullable<int> TMTID { get; set; }
        public string FileName { get; set; }
        public string RelativePath { get; set; }
        public string ContentType { get; set; }
        public int ByteLength { get; set; }
        public byte[] PhotoBytes { get; set; }
        public System.DateTime SavedUtc { get; set; }
        public int ByUserID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TechnicalMapAssembly TechnicalMapAssembly { get; set; }
        public virtual TechnicalMapTesting TechnicalMapTesting { get; set; }
        public virtual UsersProfile UsersProfile { get; set; }
    }
}
