//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentWithoutTesting
    {
        public int ShipmentID { get; set; }
        public int ActID { get; set; }
        public int UserID { get; set; }
        public string Reason { get; set; }
        public System.DateTime ShipmentUtc { get; set; }
        public int ProductCount { get; set; }
    
        public virtual Act Act { get; set; }
        public virtual UsersProfile UsersProfile { get; set; }
    }
}
