//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalMatFlight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnicalMatFlight()
        {
            this.TestFlight = new HashSet<TestFlight>();
        }
    
        public int TFlightID { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public bool Test_Pass { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UsersProfile UsersProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestFlight> TestFlight { get; set; }
    }
}
