//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalMapAssembly
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechnicalMapAssembly()
        {
            this.Description1 = new HashSet<Description>();
            this.ProductPhoto = new HashSet<ProductPhoto>();
        }
    
        public int TMAID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public System.TimeSpan TimeEnd { get; set; }
        public bool InProgress { get; set; }
        public bool IsReady { get; set; }
        public bool Fault { get; set; }
        public Nullable<int> DescriptionID { get; set; }
        public int TMID { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual TechnicalMapFull TechnicalMapFull { get; set; }
        public virtual UsersProfile UsersProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Description> Description1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPhoto> ProductPhoto { get; set; }
    }
}
