//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestFlight
    {
        public int TestID { get; set; }
        public bool Visual { get; set; }
        public bool Damage { get; set; }
        public bool FC1 { get; set; }
        public bool FC2 { get; set; }
        public bool C_5V_FC1 { get; set; }
        public bool C_5V_FC2 { get; set; }
        public bool FC_Test_Pass { get; set; }
        public bool Externa_Test_Pass { get; set; }
        public bool Long_Test_Pass { get; set; }
        public string Result { get; set; }
        public string Description { get; set; }
        public int TFlightID { get; set; }
        public int Stand { get; set; }
    
        public virtual TechnicalMatFlight TechnicalMatFlight { get; set; }
    }
}
