//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData1.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWithPermissions
    {
        public int PermAddID { get; set; }
        public int UserID { get; set; }
        public int PermissionsID { get; set; }
    
        public virtual Permissions Permissions { get; set; }
        public virtual UsersProfile UsersProfile { get; set; }
    }
}
